#include "main.h"
#include "io.h"
#include "ez_array.h"

#include <GL/glew.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>

typedef struct {

	int w, h;
	GLuint obj; // texture object generated by glGenTextures

} TextureGL;

typedef struct {

	GLuint vertex_array; // "VAO"
	uint vertex_count;
	TextureGL *texture_gl;

} MeshGL;

static const char *vertex3D =
"#version 150 core\n"
"uniform mat4 position_matrix;\n"
"uniform mat4 normal_matrix;\n"
"in vec3 position;\n"
"in vec3 normal;\n"
"in vec2 UV;\n"
"out vec3 normal_camera;\n"
"out vec2 frag_UV;\n"
"void main() {\n"
    "gl_Position = position_matrix * vec4(position.xyz, 1.0);\n" // get final position
    "normal_camera = (normal_matrix * vec4(normal, 1.0)).xyz;\n" // get final normal
    "frag_UV = UV;\n" // pass along UV
"}";

static const char *fragment3D =
"#version 150 core\n"
"uniform sampler2D tex;\n"
"in vec3 normal_camera;\n"
"in vec2 frag_UV;\n"
"out vec4 outColor;\n"
"void main() {\n"
	"float c = dot(normal_camera, vec3(0.7, 0.7, 0)) * 0.3 + 0.7;\n"
	"outColor = texture(tex, frag_UV) * vec4(c, c, c, 1.0);\n"
	"if (outColor.a == 0) { discard; }" // texture clip transparency
"}";

static const char *vertexSky =
"#version 150 core\n"
"in vec2 position;\n"
"out float height;\n" // [-1, 1]
"void main() {\n"
    "gl_Position = vec4(position.xy, -1.0, 1.0);\n" // get final position
	"height = position.y;\n"
"}";

static const char *fragmentSky =
"#version 150 core\n"
"uniform vec2 rotation;\n" // pitch [-1, 1] yaw [0, 1]
"in float height;\n"
"out vec4 outColor;\n"
"void main() {\n"
	"outColor = mix(vec4(0.4, 0.55, 1.0, 1.0), vec4(0.58, 0.73, 1.0, 1.0), clamp((height * 10.0) * 0.5 + 0.5 + 5.0 * tan(rotation.x * 1.57), 0.0, 1.0));\n"
"}";

static const char *vertex2D =
"#version 150 core\n"
"in vec2 position;\n"
"in vec2 UV;\n"
"out vec2 frag_UV;\n"
"void main() {\n"
    "gl_Position = vec4(position.xy, -1.0, 1.0);\n" // get final position
    "frag_UV = UV;\n" // pass along UV
"}";

static const char *fragment2D =
"#version 150 core\n"
"uniform sampler2D tex;\n"
"in vec2 frag_UV;\n"
"out vec4 outColor;\n"
"void main() {\n"
	"outColor = texture(tex, frag_UV);\n"
"}";

// hardcoded values of near plane = 0.01, far plane = 100
#define PROJ_MATRIX (GLfloat[][4]) {\
    { WINDOW_HEIGHT / (float) WINDOW_WIDTH / tan(FOV * M_PI / 360.0), 0, 0, 0 },\
    { 0, 1.0 / tan(FOV * M_PI / 360.0), 0, 0 },\
    { 0, 0, -1.00020002, -1.0 },\
    { 0, 0, -0.0200020002, 0 }\
}

static GLuint shader3D_program;
static GLuint shaderSky_program;
static GLuint shader2D_program;

static SDL_Window *window;
static int running = 1;

static void log_error(const char *msg) {
	
	if (strlen(SDL_GetError()) == 0) {
		fprintf(stderr, "\n%s: <No error given>\n\n", msg);
	} else {
		fprintf(stderr, "\n%s: %s\n\n", msg, SDL_GetError());
	}
}

static void create_shader_program(GLuint *const program_out, const char *vertex_code, const char *fragment_code) {

	*program_out = glCreateProgram();

	GLuint vertex_shader = glCreateShader(GL_VERTEX_SHADER);
	glShaderSource(vertex_shader, 1, (const char *const *) &vertex_code, NULL);
	glCompileShader(vertex_shader);
	glAttachShader(*program_out, vertex_shader);

	GLuint fragment_shader = glCreateShader(GL_FRAGMENT_SHADER);
	glShaderSource(fragment_shader, 1, (const char *const *) &fragment_code, NULL);
	glCompileShader(fragment_shader);
	glAttachShader(*program_out, fragment_shader);

	glLinkProgram(*program_out);
}

void initialize_io() {

    if (SDL_Init(SDL_INIT_VIDEO) != 0) {
		log_error("Could not initialize SDL");
		exit(1);
	}

	// init OpenGL
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
	SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

	window = SDL_CreateWindow("CinnamonCraft", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, WINDOW_WIDTH, WINDOW_HEIGHT, SDL_WINDOW_OPENGL);

	if (!window) {
        log_error("Could not create window");
		exit(1);
    }

	SDL_GLContext context = SDL_GL_CreateContext(window);

	glewExperimental = GL_TRUE;
	glewInit();

	glEnable(GL_DEPTH_TEST);
	glEnable(GL_CULL_FACE);
	glFrontFace(GL_CCW);
	glClearColor(1.0f, 0.188f, 0.647f, 1.0f); // since the sky is rendered as a mesh, set the clear color to hot pink so it's obvious

	SDL_SetRelativeMouseMode(SDL_TRUE);

    create_shader_program(&shader3D_program, vertex3D, fragment3D);
	create_shader_program(&shaderSky_program, vertexSky, fragmentSky);
	create_shader_program(&shader2D_program, vertex2D, fragment2D);
}

int game_is_running() {

    return running;
}

void populate_input(Input *input) {

    input->camera_dx = 0.0;
    input->camera_dy = 0.0;

    input->use = 0; // TODO replace with logical cooldown (for block placement)

    SDL_Event event;

    while (SDL_PollEvent(&event)) {

        if (event.type == SDL_QUIT) {

            running = 0;
        
        } else if (event.type == SDL_MOUSEMOTION) {

            input->camera_dx = (int) event.motion.xrel; // Sint32
            input->camera_dy = (int) event.motion.yrel;

        } else if (event.type == SDL_KEYDOWN && event.key.repeat == 0) {

            if (event.key.keysym.scancode == SDL_SCANCODE_A) {
                input->left = 1;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_D) {
                input->right = 1;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_W) {
                input->forward = 1;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_S) {
                input->backward = 1;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_SPACE) {
                input->up = 1;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_LSHIFT) {
                input->down = 1;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_ESCAPE) {
                SDL_SetRelativeMouseMode(!SDL_GetRelativeMouseMode());
            }

        } else if (event.type == SDL_KEYUP) {

            if (event.key.keysym.scancode == SDL_SCANCODE_A) {
                input->left = 0;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_D) {
                input->right = 0;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_W) {
                input->forward = 0;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_S) {
                input->backward = 0;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_SPACE) {
                input->up = 0;
            } else if (event.key.keysym.scancode == SDL_SCANCODE_LSHIFT) {
                input->down = 0;
            }

        } else if (event.type == SDL_MOUSEBUTTONDOWN) {

            if (event.button.button == 1) { // LMB
                input->attack = 1;
            } else if (event.button.button == 3) { // RMB
                input->use = 1;
            }
        }

        else if (event.type == SDL_MOUSEBUTTONUP) {

            if (event.button.button == 1) { // LMB
                input->attack = 0;
            } else if (event.button.button == 3) { // RMB
                input->use = 0;
            }
        }
    }
}

void present() {

    SDL_GL_SwapWindow(window);
    SDL_Delay(1000 / 60);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
}

Texture load_texture(const char *path) {

	TextureGL *texture_gl = malloc(sizeof(TextureGL));

	SDL_Surface *surface = IMG_Load(path);
	
	texture_gl->w = surface->w;
	texture_gl->h = surface->h;

	// flip texture vertically to match OpenGL spec
	unsigned char *pixels = (unsigned char *) surface->pixels;
	int pixelBytes = surface->format->BytesPerPixel;

	for (int y = 0; y < surface->h / 2; y++) {

		for (int x = 0; x < surface->w; x++) {

			int top = x + y * surface->h;
			int bottom = x + (surface->w * surface->h - (y + 1) * surface->h);

			for (int i=0; i<pixelBytes; i++) {

				unsigned char hold = pixels[top * pixelBytes + i];
				pixels[top * pixelBytes + i] = pixels[bottom * pixelBytes + i];
				pixels[bottom * pixelBytes + i] = hold;
			}
		}
	}

	// create texture object
	glGenTextures(1, &texture_gl->obj);

	// bind texture (to active texture 2D)
	glBindTexture(GL_TEXTURE_2D, texture_gl->obj);

	// wrap repeat
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);

	// filter linear
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

	// write texture data
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, surface->w, surface->h, 0, GL_RGBA, GL_UNSIGNED_BYTE, surface->pixels);

	// clean up
	SDL_FreeSurface(surface);

	return texture_gl;
}

void free_texture(Texture texture) {

	glDeleteTextures(1, &((TextureGL *) texture)->obj);
	free(texture);
}

void remesh_mesh(Mesh mesh, const unsigned char *mesh_data, const int mesh_bytecount, const int mesh_vertcount) {

	// make vertex array
	GLuint vertex_array;
	glGenVertexArrays(1, &vertex_array);
	glBindVertexArray(vertex_array);

	// make vertex buffer (stored by vertex_array)
	GLuint vertex_buffer;
	glGenBuffers(1, &vertex_buffer);
	glBindBuffer(GL_ARRAY_BUFFER, vertex_buffer);								// make it the active buffer
	glBufferData(GL_ARRAY_BUFFER, mesh_bytecount, mesh_data, GL_STATIC_DRAW);	// copy vertex data into the active buffer

	// link active vertex data and shader attributes
	GLint pos_attrib = glGetAttribLocation(shader3D_program, "position");
	glVertexAttribPointer(pos_attrib, 3, GL_FLOAT, GL_FALSE, sizeof(float) * 8, 0);
	glEnableVertexAttribArray(pos_attrib); // requires a VAO to be bound

	GLint normal_attrib = glGetAttribLocation(shader3D_program, "normal");
	glVertexAttribPointer(normal_attrib, 3, GL_FLOAT, GL_FALSE, sizeof(float) * 8, (GLvoid *) (sizeof(float) * 3));
	glEnableVertexAttribArray(normal_attrib);

	GLint uv_attrib = glGetAttribLocation(shader3D_program, "UV");
	glVertexAttribPointer(uv_attrib, 2, GL_FLOAT, GL_FALSE, sizeof(float) * 8, (GLvoid *) (sizeof(float) * 6));
	glEnableVertexAttribArray(uv_attrib);

	// debind vertex array
	glBindVertexArray(0);

	// assign to mesh, freeing previous VAO if it exists
	MeshGL *mesh_gl = (MeshGL *) mesh;

	if (mesh_gl->vertex_array)
		glDeleteVertexArrays(1, &mesh_gl->vertex_array);

	mesh_gl->vertex_array = vertex_array;
	mesh_gl->vertex_count = mesh_vertcount;
}

void mesh_set_texture(Mesh mesh, Texture texture) {

	((MeshGL *) mesh)->texture_gl = (TextureGL *) texture;
}

void free_mesh(Mesh mesh) {

	glDeleteVertexArrays(1, &((MeshGL *) mesh)->vertex_array);
	free(mesh);
}

Mesh create_mesh(const unsigned char *mesh_data, const int mesh_bytecount, const int mesh_vertcount, Texture texture) {

	Mesh mesh = malloc(sizeof(MeshGL));

	remesh_mesh(mesh, mesh_data, mesh_bytecount, mesh_vertcount);	
	mesh_set_texture(mesh, texture);

	return mesh;
}

Mesh create_mesh_from_obj(const char *obj_path, Texture texture) {

	// read obj file
	FILE *file = fopen(obj_path, "r");

	if (file == NULL) {
		printf("File \"%s\" does not exist!\n", obj_path);
		exit(1);
	}

	char line[1024];

	EZArray position_data  = {0};
	EZArray normal_data    = {0};
	EZArray texture_data   = {0};
	EZArray composite_data = {0}; // stores combined vertex position, normal, and texture data

	int vertex_count;

	while (fgets(line, 1024, file)) {

		char prefix[8];

		sscanf(line, "%s", prefix);

		if (!strcmp(prefix, "v")) {

			float v[3];
			
			sscanf(line, "v %f %f %f", &v[0], &v[1], &v[2]);

			// obj vertices have reverse xz
			v[0] = -v[0];
			v[2] = -v[2];

			append_ezarray(&position_data, v, sizeof(float) * 3);
		}

		else if (!strcmp(prefix, "vn")) {

			float n[3];
			
			sscanf(line, "vn %f %f %f", &n[0], &n[1], &n[2]);

			// obj vertices have reverse xz
			n[0] = -n[0];
			n[2] = -n[2];

			append_ezarray(&normal_data, n, sizeof(float) * 3);
		}

		else if (!strcmp(prefix, "vt")) {

			float n[2];
			
			sscanf(line, "vt %f %f", &n[0], &n[1]);

			append_ezarray(&texture_data, n, sizeof(float) * 2);
		}

		else if (!strcmp(prefix, "f")) {

			// only works with tris right now (no quads or ngons)

			unsigned int p[3]; // vertex position indices
			unsigned int t[3]; // vertex texture coordinate indices
			unsigned int n[3]; // vertex normal indices
			
			sscanf(line, "f %u/%u/%u %u/%u/%u %u/%u/%u",
				&p[0], &t[0], &n[0],
				&p[1], &t[1], &n[1],
				&p[2], &t[2], &n[2]);

			// convert vertex indices to vertex positions (indices start at 1 for some reason)
			append_ezarray(&composite_data, position_data.data + ((p[0] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, normal_data.data +   ((n[0] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, texture_data.data +  ((t[0] - 1) * sizeof(float) * 2), sizeof(float) * 2);

			append_ezarray(&composite_data, position_data.data + ((p[1] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, normal_data.data +   ((n[1] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, texture_data.data +  ((t[1] - 1) * sizeof(float) * 2), sizeof(float) * 2);

			append_ezarray(&composite_data, position_data.data + ((p[2] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, normal_data.data +   ((n[2] - 1) * sizeof(float) * 3), sizeof(float) * 3);
			append_ezarray(&composite_data, texture_data.data +  ((t[2] - 1) * sizeof(float) * 2), sizeof(float) * 2);
			
			vertex_count += 3;
		}
	}

	fclose(file);

	// create mesh
	return create_mesh(composite_data.data, composite_data.bytecount, vertex_count, texture);
}

static void mat4_mult(const GLfloat b[4][4], const GLfloat a[4][4], GLfloat out[4][4]) {

	// a (rightmost) is applied first, then b

	GLfloat matrix[4][4] = {
		{
			a[0][0] * b[0][0] + a[0][1] * b[1][0] + a[0][2] * b[2][0] + a[0][3] * b[3][0],
			a[0][0] * b[0][1] + a[0][1] * b[1][1] + a[0][2] * b[2][1] + a[0][3] * b[3][1],
			a[0][0] * b[0][2] + a[0][1] * b[1][2] + a[0][2] * b[2][2] + a[0][3] * b[3][2],
			a[0][0] * b[0][3] + a[0][1] * b[1][3] + a[0][2] * b[2][3] + a[0][3] * b[3][3],
		},
		{
			a[1][0] * b[0][0] + a[1][1] * b[1][0] + a[1][2] * b[2][0] + a[1][3] * b[3][0],
			a[1][0] * b[0][1] + a[1][1] * b[1][1] + a[1][2] * b[2][1] + a[1][3] * b[3][1],
			a[1][0] * b[0][2] + a[1][1] * b[1][2] + a[1][2] * b[2][2] + a[1][3] * b[3][2],
			a[1][0] * b[0][3] + a[1][1] * b[1][3] + a[1][2] * b[2][3] + a[1][3] * b[3][3],
		},
		{
			a[2][0] * b[0][0] + a[2][1] * b[1][0] + a[2][2] * b[2][0] + a[2][3] * b[3][0],
			a[2][0] * b[0][1] + a[2][1] * b[1][1] + a[2][2] * b[2][1] + a[2][3] * b[3][1],
			a[2][0] * b[0][2] + a[2][1] * b[1][2] + a[2][2] * b[2][2] + a[2][3] * b[3][2],
			a[2][0] * b[0][3] + a[2][1] * b[1][3] + a[2][2] * b[2][3] + a[2][3] * b[3][3],
		},
		{
			a[3][0] * b[0][0] + a[3][1] * b[1][0] + a[3][2] * b[2][0] + a[3][3] * b[3][0],
			a[3][0] * b[0][1] + a[3][1] * b[1][1] + a[3][2] * b[2][1] + a[3][3] * b[3][1],
			a[3][0] * b[0][2] + a[3][1] * b[1][2] + a[3][2] * b[2][2] + a[3][3] * b[3][2],
			a[3][0] * b[0][3] + a[3][1] * b[1][3] + a[3][2] * b[2][3] + a[3][3] * b[3][3],
		},
	};

	int x, y;

	for (x = 0; x < 4; x++) {
		for (y = 0; y < 4; y++) {
			out[x][y] = matrix[x][y];
		}
	}
}

static void generate_rotation_matrices(GLfloat pitch_matrix[4][4], float pitch, GLfloat yaw_matrix[4][4], float yaw) {

	pitch_matrix[0][0] = 1;
	pitch_matrix[0][1] = 0;
	pitch_matrix[0][2] = 0;
	pitch_matrix[0][3] = 0;

	pitch_matrix[1][0] = 0;
	pitch_matrix[1][1] = cos(pitch);
	pitch_matrix[1][2] = -sin(pitch);
	pitch_matrix[1][3] = 0;

	pitch_matrix[2][0] = 0;
	pitch_matrix[2][1] = sin(pitch);
	pitch_matrix[2][2] = cos(pitch);
	pitch_matrix[2][3] = 0;

	pitch_matrix[3][0] = 0;
	pitch_matrix[3][1] = 0;
	pitch_matrix[3][2] = 0;
	pitch_matrix[3][3] = 1;

	yaw_matrix[0][0] = cos(yaw);
	yaw_matrix[0][1] = 0;
	yaw_matrix[0][2] = sin(yaw);
	yaw_matrix[0][3] = 0;

	yaw_matrix[1][0] = 0;
	yaw_matrix[1][1] = 1;
	yaw_matrix[1][2] = 0;
	yaw_matrix[1][3] = 0;

	yaw_matrix[2][0] = -sin(yaw);
	yaw_matrix[2][1] = 0;
	yaw_matrix[2][2] = cos(yaw);
	yaw_matrix[2][3] = 0;

	yaw_matrix[3][0] = 0;
	yaw_matrix[3][1] = 0;
	yaw_matrix[3][2] = 0;
	yaw_matrix[3][3] = 1;
}

void draw_mesh(const Transform *camera, const Transform *transform, const Mesh mesh) {

	// shared buffers
	GLfloat pitch_matrix[4][4];
	GLfloat yaw_matrix[4][4];

	GLfloat position_matrix[4][4];

	// bind the mesh's vertex mesh and texture
	glBindVertexArray(((MeshGL *) mesh)->vertex_array);
	glBindTexture(GL_TEXTURE_2D, ((MeshGL *) mesh)->texture_gl->obj);

	// model matrix (converts from model space to world space)
	generate_rotation_matrices(
		pitch_matrix, transform->pitch,
		yaw_matrix, transform->yaw
	);

	GLfloat model_matrix[4][4];

	mat4_mult(yaw_matrix, pitch_matrix, model_matrix); // rotation

	model_matrix[3][0] = transform->x; // translation
	model_matrix[3][1] = transform->y;
	model_matrix[3][2] = transform->z;

	// view matrix (converts from world space to view space, aka accounts for camera transformations)
	// must apply translations before rotations this time, unlike model matrix!
	generate_rotation_matrices(
		pitch_matrix, -camera->pitch,
		yaw_matrix, -camera->yaw
	);

	GLfloat view_matrix[4][4] = {
		{1, 0, 0, 0},
		{0, 1, 0, 0},
		{0, 0, 1, 0},
		{-camera->x, -camera->y, -camera->z, 1}
	};

	mat4_mult(yaw_matrix, view_matrix, view_matrix);
	mat4_mult(pitch_matrix, view_matrix, view_matrix);

	// final position matrix (PROJ_MATRIX * view_matrix * model_matrix)
	mat4_mult(PROJ_MATRIX, view_matrix, position_matrix);
	mat4_mult(position_matrix, model_matrix, position_matrix);

	// normal matrix (applied to normals to account for mesh rotation)
	GLfloat normal_matrix[4][4];

	generate_rotation_matrices(
		pitch_matrix, -transform->pitch,
		yaw_matrix, -transform->yaw
	);

	mat4_mult(yaw_matrix, pitch_matrix, normal_matrix);

	// load the 3D shader program and the uniforms we just calculated
	glUseProgram(shader3D_program);
	glUniformMatrix4fv(glGetUniformLocation(shader3D_program, "position_matrix"), 1, GL_FALSE, &position_matrix[0][0]);
	glUniformMatrix4fv(glGetUniformLocation(shader3D_program, "normal_matrix"), 1, GL_FALSE, &normal_matrix[0][0]);

	// draw
	glDrawArrays(GL_TRIANGLES, 0, ((MeshGL *) mesh)->vertex_count);
}

Mesh create_sky_mesh() {

	const float mesh_data[] = {
		-1.0f, -1.0f,
		 1.0f, -1.0f,
		-1.0f,  1.0f,
		 1.0f, -1.0f,
		 1.0f,  1.0f,
		-1.0f,  1.0f,
	};

	static const int mesh_vertcount = 6;
	static const int mesh_bytecount = sizeof(float) * 2 * mesh_vertcount;

	// make vertex array
	GLuint vertex_array;
	glGenVertexArrays(1, &vertex_array);
	glBindVertexArray(vertex_array);

	// make vertex buffer (stored by vertex_array)
	GLuint vertex_buffer;
	glGenBuffers(1, &vertex_buffer);
	glBindBuffer(GL_ARRAY_BUFFER, vertex_buffer);								// make it the active buffer
	glBufferData(GL_ARRAY_BUFFER, mesh_bytecount, mesh_data, GL_STATIC_DRAW);	// copy vertex data into the active buffer

	// link active vertex data and shader attributes
	GLint pos_attrib = glGetAttribLocation(shaderSky_program, "position");
	glVertexAttribPointer(pos_attrib, 2, GL_FLOAT, GL_FALSE, sizeof(float) * 2, 0);
	glEnableVertexAttribArray(pos_attrib); // requires a VAO to be bound

	// debind vertex array
	glBindVertexArray(0);

	// create final mesh object to return
	MeshGL *mesh_gl = malloc(sizeof(MeshGL));
	mesh_gl->vertex_array = vertex_array;
	mesh_gl->vertex_count = mesh_vertcount;

	return mesh_gl;
}

void draw_sky_mesh(const Transform *camera, const Mesh mesh) {

	glDisable(GL_DEPTH_TEST);

	glBindVertexArray(((MeshGL *) mesh)->vertex_array);
	glUseProgram(shaderSky_program);
	glUniform2f(glGetUniformLocation(shaderSky_program, "rotation"), (GLfloat) -camera->pitch * 2.0 / M_PI, (GLfloat) fmod(fmod(camera->yaw / 2.0 / M_PI, 1.0) + 1.0, 1.0));

	glDrawArrays(GL_TRIANGLES, 0, ((MeshGL *) mesh)->vertex_count);

	glEnable(GL_DEPTH_TEST);
}

Mesh create_sprite_mesh(float u, float v, float h, Texture texture) {
	
	const float w = h * WINDOW_HEIGHT / WINDOW_WIDTH * ((TextureGL *) texture)->h / ((TextureGL *) texture)->w;

	const float mesh_data[] = {
		u,     v,     0.0f, 0.0f,
		u + w, v,     1.0f, 0.0f,
		u,     v + h, 0.0f, 1.0f,
		u + w, v,     1.0f, 0.0f,
		u + w, v + h, 1.0f, 1.0f,
		u,     v + h, 0.0f, 1.0f
	};

	static const int mesh_vertcount = 6;
	static const int mesh_bytecount = sizeof(float) * 4 * mesh_vertcount;

	// make vertex array
	GLuint vertex_array;
	glGenVertexArrays(1, &vertex_array);
	glBindVertexArray(vertex_array);

	// make vertex buffer (stored by vertex_array)
	GLuint vertex_buffer;
	glGenBuffers(1, &vertex_buffer);
	glBindBuffer(GL_ARRAY_BUFFER, vertex_buffer);								// make it the active buffer
	glBufferData(GL_ARRAY_BUFFER, mesh_bytecount, mesh_data, GL_STATIC_DRAW);	// copy vertex data into the active buffer

	// link active vertex data and shader attributes
	GLint pos_attrib = glGetAttribLocation(shader2D_program, "position");
	glVertexAttribPointer(pos_attrib, 2, GL_FLOAT, GL_FALSE, sizeof(float) * 4, 0);
	glEnableVertexAttribArray(pos_attrib); // requires a VAO to be bound

	GLint uv_attrib = glGetAttribLocation(shader2D_program, "UV");
	glVertexAttribPointer(uv_attrib, 2, GL_FLOAT, GL_FALSE, sizeof(float) * 4, (GLvoid *) (sizeof(float) * 2));
	glEnableVertexAttribArray(uv_attrib);

	// debind vertex array
	glBindVertexArray(0);

	// create final mesh object to return
	MeshGL *mesh_gl = malloc(sizeof(MeshGL));
	mesh_gl->vertex_array = vertex_array;
	mesh_gl->vertex_count = mesh_vertcount;
	mesh_gl->texture_gl = (TextureGL *) texture;

	return mesh_gl;
}

void draw_sprite_mesh(const Mesh mesh) {

	// bind the mesh's vertex mesh and texture
	glBindVertexArray(((MeshGL *) mesh)->vertex_array);
	glBindTexture(GL_TEXTURE_2D, ((MeshGL *) mesh)->texture_gl->obj);

	// load the 2D shader program
	glUseProgram(shader2D_program);

	// draw
	glDrawArrays(GL_TRIANGLES, 0, ((MeshGL *) mesh)->vertex_count);
}